services:
    cn_toolbox.cache.filesystem:
        class: ClaviculaNox\ToolboxBundle\Classes\Services\Cache\FileSystemCacheService
        public: true
        arguments:
            - "%toolbox.fs_system_cache_path%"
            - "%toolbox.fs_system_cache_path_chmod%"
            - "%toolbox.fs_system_cache_path_default_ttl%"
            - "@filesystem"

    cn_toolbox.tools.csv_manager:
        class: ClaviculaNox\ToolboxBundle\Classes\Services\Tools\CSVManager
        public: true
        arguments:
            - "@filesystem"

    cn_toolbox.tools.integer_manager:
        class: ClaviculaNox\ToolboxBundle\Classes\Services\Tools\IntegerManager
        public: true

    cn_toolbox.tools.string_manager:
        class: ClaviculaNox\ToolboxBundle\Classes\Services\Tools\StringManager
        public: true
